config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root "home#index"
  resources :connections
  resources :dimensions
  resources :ordering_informations
  resources :technicals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @technicals = Technical.all
    @connections = Connection.all
    @ordering_informations = OrderingInformation.all
    @dimensions = Dimension.all
    @technical = Technical.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>

  <div class="container py-5">
    <div class="sectionmain mt-5 p-3">

    <h2 class="mb-4 text-center">Table Data</h2>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button">Technical Data</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button">Connection Data</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button">Ordering Information</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="diamention-tab" data-bs-toggle="tab" data-bs-target="#diamention" type="button">Diamentions</button>
      </li>
    </ul>

     <!-- Tab content -->
    <div class="tab-content p-3 mt-2" id="myTabContent">
      <!-- Home Tab Content -->
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <div class="flaxcontain">
          <h5>TECHNICAL DATA</h5>
          <%# <button class="btn btn-sm btngreen btn-danger">Add Data +</button> %>
            <%= link_to "Add Data +", new_technical_path,class: "btn btn-sm btngreen btn-danger" %>
        </div>
        <div class="table-responsive mt-3">
          <table class="table table-striped table-bordered align-middle">
            <thead class="table-dark">
              <tr>
                <th>title</th>
                <th>Unit</th>
                <th>Action</th>
                
              </tr>
            </thead>
             <tbody>
                    <% @technicals.each do |technical| %>
                      <tr>
                        <td><%=  technical.title%></td>
                        <td><%= technical.value%></td>
                        <td class="df">
                          <%= link_to  technical, class: "btn  m-2  btn-sm btn-info text-white" do %>
                            <i class="bi bi-eye"></i> 
                          <% end %>
                         
                          <%= link_to  edit_technical_path(technical), class: "btn  m-2  btn-sm btn-primary" do  %> <i class="bi bi-pencil"> </i><%end%>
                          <%= button_to  technical, method: :delete, class:"btn  m-2  btn-sm btn-danger" do %><i class="bi bi-trash"></i><%end%>
                        </td>
                      </tr>
                    <%end%>
                </tbody>
          </table>
        </div>
      </div>













      <!-- Profile Tab Content -->
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
       
        <div class="flaxcontain">
              <h5>CONNECTION DATA</h5>
              <%# <button class="btn btn-sm btngreen btn-danger"></button> %>
              <%= link_to "Add Data +", new_connection_path, class: "btn btn-sm btngreen btn-danger" %>
            </div>
        <div class="table-responsive mt-3">
          <table class="table table-hover table-bordered align-middle">
            <thead class="table-dark">
              <tr>
                <th>ID</th>
                <th>Profile Name</th>
                <th>Email</th>
                <%# <th>Status</th>
                <th>Actions</th> %>
              </tr>
            </thead>
             <tbody>
                  <% @connections.each do |connection| %>
                    <tr>
                      <td><%= connection.title%></td>
                      <td><%= connection.unit%></td>
                      <td class="df">
                        <%= link_to  connection, class: "btn   m-2 btn-sm btn-info text-white" do %>
                          <i class="bi bi-eye"></i> 
                        <% end %>
                        <%= link_to  edit_connection_path(connection), class: "btn  m-2 btn-sm btn-primary" do  %> <i class="bi bi-pencil"> </i><%end%>
                        <%= button_to  connection, method: :delete, class:"btn   m-2 btn-sm btn-danger" do %><i class="bi bi-trash"></i><%end%>
                      </td>
                    </tr>
                  <%end%>
                </tbody>
          </table>
        </div>
      </div>















      <!-- Contact Tab Content -->
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
       <div class="flaxcontain">
                 <h5>ORDERING INFORMATION</h5>
                 <%# <button class="btn btn-sm btngreen btn-danger">Add Data +</button> %>
                  <%= link_to "Add Data +", new_ordering_information_path, class: "btn btn-sm btngreen btn-danger" %>
              </div>
        <div class="table-responsive mt-3">
          <table class="table table-striped table-bordered align-middle">
                    <thead class="table-dark">
                       <tr>
                          <th>CAT. NO.</th>
                          <th>DESCRIPTION</th>
                          <th>STD. PACK</th>
                          <th></th>
                       </tr>
                    </thead>
                    <tbody>
                      <% @ordering_informations.each do |order_info| %>
                        <tr>
                          <td><%= order_info.cat_no%></td>
                          <td><%= order_info.description%></td>
                          <td><%= order_info.std_pack%></td>
                          <td class="df">
                            <%= link_to  order_info, class: "btn m-2 btn-sm btn-info text-white" do %>
                              <i class="bi bi-eye"></i> 
                            <% end %>
                            <%= link_to  edit_ordering_information_path(order_info), class: "btn  m-2 btn-sm btn-primary" do  %> <i class="bi bi-pencil"> </i><%end%>
                            <%= button_to  order_info, method: :delete, class:"btn m-2 btn-sm btn-danger" do %><i class="bi bi-trash"></i><%end%>
                          </td>
                        </tr>
                      <%end%>
                    </tbody>
                 </table>
        </div>
      </div>












      <!-- Contact Tab Content -->
      <div class="tab-pane fade" id="diamention" role="tabpanel" aria-labelledby="diamention-tab">
       <div class="flaxcontain">
                 <h5>DIMENSIONS</h5>
                 <%# <button class="btn btn-sm btngreen btn-danger">Add Data +</button> %>
                 <%= link_to "Add Data +", new_dimension_path, class: "btn btn-sm btngreen btn-danger" %>
              </div>
        <div class="table-responsive mt-3">
          <table class="table table-striped table-bordered align-middle">
                    <tbody>
                      <% @dimensions.each do |dimension| %>
                        <tr>
                          <td><%= dimension.name%></td>
                          <td><%= dimension.unit%></td>
                          <td class="df">
                            <%= link_to  dimension, class: "btn m-2  btn-sm btn-info text-white" do %>
                              <i class="bi bi-eye"></i> 
                            <% end %>
                            <%= link_to  edit_dimension_path(dimension), class: "btn  m-2 btn-sm btn-primary" do  %> <i class="bi bi-pencil"> </i><%end%>
                            <%= button_to  dimension, method: :delete, class:"btn m-2 btn-sm btn-danger" do %><i class="bi bi-trash"></i><%end%>
                          </td>
                        </tr>
                      <%end%>
                    </tbody>
                 </table>
        </div>
      </div>
    </div>
    </div>
  </div>

</body>
</html>